services:

  easyschool-back:
    container_name: easyschool-back
    image: easyschool-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - easy-school-network
    depends_on:
      - easyschool-db
    environment:
      URL: jdbc:postgresql://easyschool-db:5432/easy_school
      DB_USERNAME: db_owner
      DB_PASSWORD: easy1234
      DATABASE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 8081


  easyschool-db:
    container_name: easyschool-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: db_owner
      POSTGRES_PASSWORD: easy1234
      POSTGRES_DB: easy_school
    ports:
      - "5432:5432"
    networks:
      - easy-school-network

networks:
  easy-school-network:
    driver: bridge
