spring:
  application:
    name: easyschool-back
  datasource:
    url: ${URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: ${DATABASE_DIALECT}
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: false
server:
  port: 8081
  servlet:
    context-path: /api/v1

api:
  app:
    secret: ${SECRET:6c9c5acb3e09048b863a865d1b524c935b9cfe8c401a1d5396cd63749e02f89427d9543b31d9c0ea1e88089f8412932e2886b273d7bc7920bea814b847dc7ad1}
  jwt:
    expiration-token: 14400000



logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics