spring:
  application:
    name: easyschool-back
  datasource:
    url: ${URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: ${DATABASE_DIALECT}
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: false
server:
  port: ${SERVER_PORT}