spring:
  application:
    name: easyschool-back
  datasource:
    url: jdbc:postgresql://localhost:5432/easy_school
    username: db_owner
    password: easy1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: false
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1

api:
  app:
    secret: ${SECRET:6c9c5acb3e09048b863a865d1b524c935b9cfe8c401a1d5396cd63749e02f89427d9543b31d9c0ea1e88089f8412932e2886b273d7bc7920bea814b847dc7ad1}
  jwt:
    expiration-token: 14400000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    org.springframework.security: DEBUG
