global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "easy-school-back"
    metrics_path: "api/v1/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8081" ]
        labels:
          application: "easy-school-back"